import type { InsertAchievement } from "./schema";

type AchievementDef = Omit<InsertAchievement, "unlockedAt">;

export const ALL_ACHIEVEMENTS: AchievementDef[] = [
  // STREAKS (1-25)
  { key: "streak_3", title: "Getting Started", description: "Maintain a 3-day streak", icon: "Flame", category: "streaks", tier: "bronze", xpReward: 100, goldReward: 10 },
  { key: "streak_7", title: "Week Warrior", description: "Maintain a 7-day streak", icon: "Flame", category: "streaks", tier: "bronze", xpReward: 250, goldReward: 25 },
  { key: "streak_14", title: "Fortnight Fighter", description: "Maintain a 14-day streak", icon: "Flame", category: "streaks", tier: "silver", xpReward: 500, goldReward: 50 },
  { key: "streak_21", title: "Three Week Titan", description: "Maintain a 21-day streak", icon: "Flame", category: "streaks", tier: "silver", xpReward: 750, goldReward: 75 },
  { key: "streak_30", title: "Monthly Master", description: "Maintain a 30-day streak", icon: "Flame", category: "streaks", tier: "gold", xpReward: 1000, goldReward: 100 },
  { key: "streak_45", title: "Iron Will", description: "Maintain a 45-day streak", icon: "Flame", category: "streaks", tier: "gold", xpReward: 1500, goldReward: 150 },
  { key: "streak_60", title: "Diamond Discipline", description: "Maintain a 60-day streak", icon: "Flame", category: "streaks", tier: "platinum", xpReward: 2000, goldReward: 200, statBonus: { stat: "willpower", amount: 5 } },
  { key: "streak_90", title: "Quarterly Champion", description: "Maintain a 90-day streak", icon: "Flame", category: "streaks", tier: "platinum", xpReward: 3000, goldReward: 300, statBonus: { stat: "willpower", amount: 10 } },
  { key: "streak_180", title: "Half-Year Hero", description: "Maintain a 180-day streak", icon: "Flame", category: "streaks", tier: "legendary", xpReward: 5000, goldReward: 500, statBonus: { stat: "willpower", amount: 15 }, specialPower: "Double XP on weekends" },
  { key: "streak_365", title: "Year of Power", description: "Maintain a 365-day streak", icon: "Crown", category: "streaks", tier: "legendary", xpReward: 10000, goldReward: 1000, statBonus: { stat: "willpower", amount: 25 }, specialPower: "Permanent 10% XP boost" },
  { key: "comeback_3", title: "Rising Again", description: "Recover a 3-day streak after breaking", icon: "RotateCcw", category: "streaks", tier: "bronze", xpReward: 150, goldReward: 15 },
  { key: "comeback_7", title: "Phoenix Rising", description: "Recover a 7-day streak after breaking", icon: "RotateCcw", category: "streaks", tier: "silver", xpReward: 400, goldReward: 40 },
  { key: "comeback_30", title: "Unstoppable Force", description: "Recover a 30-day streak after breaking", icon: "RotateCcw", category: "streaks", tier: "gold", xpReward: 1000, goldReward: 100 },
  { key: "streak_multi_3", title: "Multi-Tasker", description: "Maintain 3 habits with 7+ day streaks", icon: "Layers", category: "streaks", tier: "silver", xpReward: 500, goldReward: 50 },
  { key: "streak_multi_5", title: "Habit Master", description: "Maintain 5 habits with 7+ day streaks", icon: "Layers", category: "streaks", tier: "gold", xpReward: 1000, goldReward: 100 },
  { key: "streak_multi_10", title: "Discipline Incarnate", description: "Maintain 10 habits with 7+ day streaks", icon: "Layers", category: "streaks", tier: "legendary", xpReward: 2500, goldReward: 250, statBonus: { stat: "agility", amount: 10 } },
  { key: "weekend_warrior", title: "Weekend Warrior", description: "Complete habits every weekend for a month", icon: "Calendar", category: "streaks", tier: "silver", xpReward: 600, goldReward: 60 },
  { key: "early_bird_7", title: "Early Bird", description: "Complete a habit before 7AM for 7 days", icon: "Sunrise", category: "streaks", tier: "silver", xpReward: 400, goldReward: 40, statBonus: { stat: "vitality", amount: 3 } },
  { key: "night_owl_7", title: "Night Owl", description: "Complete a habit after 10PM for 7 days", icon: "Moon", category: "streaks", tier: "silver", xpReward: 400, goldReward: 40, statBonus: { stat: "sense", amount: 3 } },
  { key: "perfect_week", title: "Perfect Week", description: "Complete all habits for 7 consecutive days", icon: "CheckCircle", category: "streaks", tier: "gold", xpReward: 1200, goldReward: 120 },
  { key: "perfect_month", title: "Perfect Month", description: "Complete all habits for 30 consecutive days", icon: "CheckCircle", category: "streaks", tier: "legendary", xpReward: 5000, goldReward: 500, statBonus: { stat: "willpower", amount: 20 }, specialPower: "Unlock exclusive avatar frame" },
  { key: "consistency_king", title: "Consistency King", description: "90% completion rate for 30 days", icon: "TrendingUp", category: "streaks", tier: "gold", xpReward: 1500, goldReward: 150 },
  { key: "no_breaks", title: "No Breaks", description: "Don't skip any scheduled habits for 14 days", icon: "Shield", category: "streaks", tier: "silver", xpReward: 700, goldReward: 70 },
  { key: "daily_grind_100", title: "Daily Grind", description: "Complete 100 total habit check-ins", icon: "Activity", category: "streaks", tier: "silver", xpReward: 500, goldReward: 50 },
  { key: "daily_grind_500", title: "Relentless", description: "Complete 500 total habit check-ins", icon: "Activity", category: "streaks", tier: "gold", xpReward: 1500, goldReward: 150 },

  // LEVELS (26-50)
  { key: "level_5", title: "Rising Star", description: "Reach Level 5", icon: "Star", category: "levels", tier: "bronze", xpReward: 500, goldReward: 50 },
  { key: "level_10", title: "Seasoned Adventurer", description: "Reach Level 10", icon: "Star", category: "levels", tier: "silver", xpReward: 1000, goldReward: 100 },
  { key: "level_15", title: "Veteran", description: "Reach Level 15", icon: "Star", category: "levels", tier: "silver", xpReward: 1500, goldReward: 150 },
  { key: "level_20", title: "Expert", description: "Reach Level 20", icon: "Crown", category: "levels", tier: "gold", xpReward: 2000, goldReward: 200 },
  { key: "level_25", title: "Elite Champion", description: "Reach Level 25", icon: "Crown", category: "levels", tier: "gold", xpReward: 2500, goldReward: 250 },
  { key: "level_30", title: "Master", description: "Reach Level 30", icon: "Crown", category: "levels", tier: "gold", xpReward: 3000, goldReward: 300, statBonus: { stat: "intelligence", amount: 5 } },
  { key: "level_40", title: "Grandmaster", description: "Reach Level 40", icon: "Shield", category: "levels", tier: "platinum", xpReward: 4000, goldReward: 400, statBonus: { stat: "strength", amount: 5 } },
  { key: "level_50", title: "Legendary Hero", description: "Reach Level 50", icon: "Shield", category: "levels", tier: "platinum", xpReward: 5000, goldReward: 500, statBonus: { stat: "vitality", amount: 10 }, specialPower: "Unlock S-Rank missions" },
  { key: "level_60", title: "Mythic Guardian", description: "Reach Level 60", icon: "Sword", category: "levels", tier: "platinum", xpReward: 6000, goldReward: 600, statBonus: { stat: "agility", amount: 10 } },
  { key: "level_70", title: "Titan", description: "Reach Level 70", icon: "Sword", category: "levels", tier: "platinum", xpReward: 7000, goldReward: 700, statBonus: { stat: "sense", amount: 10 } },
  { key: "level_80", title: "Demigod", description: "Reach Level 80", icon: "Sword", category: "levels", tier: "legendary", xpReward: 8000, goldReward: 800, statBonus: { stat: "willpower", amount: 15 } },
  { key: "level_90", title: "Ascended", description: "Reach Level 90", icon: "Sparkles", category: "levels", tier: "legendary", xpReward: 9000, goldReward: 900, statBonus: { stat: "intelligence", amount: 15 } },
  { key: "level_100", title: "Shadow Monarch", description: "Reach Level 100 - Ultimate Power", icon: "Crown", category: "levels", tier: "legendary", xpReward: 15000, goldReward: 1500, statBonus: { stat: "strength", amount: 25 }, specialPower: "Unlock Shadow Realm challenges" },
  { key: "fast_leveler", title: "Fast Leveler", description: "Gain 5 levels in one week", icon: "Zap", category: "levels", tier: "silver", xpReward: 800, goldReward: 80 },
  { key: "xp_hunter_1k", title: "XP Hunter", description: "Earn 1,000 total XP", icon: "Target", category: "levels", tier: "bronze", xpReward: 100, goldReward: 10 },
  { key: "xp_hunter_10k", title: "XP Collector", description: "Earn 10,000 total XP", icon: "Target", category: "levels", tier: "silver", xpReward: 500, goldReward: 50 },
  { key: "xp_hunter_50k", title: "XP Hoarder", description: "Earn 50,000 total XP", icon: "Target", category: "levels", tier: "gold", xpReward: 2000, goldReward: 200 },
  { key: "xp_hunter_100k", title: "XP Legend", description: "Earn 100,000 total XP", icon: "Target", category: "levels", tier: "platinum", xpReward: 5000, goldReward: 500 },
  { key: "xp_hunter_500k", title: "XP Immortal", description: "Earn 500,000 total XP", icon: "Target", category: "levels", tier: "legendary", xpReward: 15000, goldReward: 1500, specialPower: "Golden XP particles effect" },
  { key: "daily_xp_500", title: "Daily Champion", description: "Earn 500 XP in a single day", icon: "Flame", category: "levels", tier: "silver", xpReward: 300, goldReward: 30 },
  { key: "daily_xp_1000", title: "XP Blitz", description: "Earn 1,000 XP in a single day", icon: "Flame", category: "levels", tier: "gold", xpReward: 600, goldReward: 60 },
  { key: "rank_novice", title: "Novice Hunter", description: "Achieve Novice Hunter rank", icon: "Shield", category: "levels", tier: "bronze", xpReward: 300, goldReward: 30 },
  { key: "rank_skilled", title: "Skilled Hunter", description: "Achieve Skilled Hunter rank", icon: "Shield", category: "levels", tier: "silver", xpReward: 600, goldReward: 60 },
  { key: "rank_elite", title: "Elite Hunter", description: "Achieve Elite Hunter rank", icon: "Shield", category: "levels", tier: "gold", xpReward: 1200, goldReward: 120 },
  { key: "rank_srank", title: "S-Rank Hunter", description: "Achieve S-Rank Hunter status", icon: "Shield", category: "levels", tier: "legendary", xpReward: 3000, goldReward: 300, specialPower: "S-Rank badge on profile" },

  // HABITS (51-90)
  { key: "first_habit", title: "Habit Former", description: "Create your first habit", icon: "Zap", category: "habits", tier: "bronze", xpReward: 100, goldReward: 10 },
  { key: "habits_5", title: "Building Foundation", description: "Create 5 habits", icon: "Layers", category: "habits", tier: "bronze", xpReward: 250, goldReward: 25 },
  { key: "habits_10", title: "Habit Collector", description: "Create 10 habits", icon: "Layers", category: "habits", tier: "silver", xpReward: 500, goldReward: 50 },
  { key: "habits_15", title: "Habit Enthusiast", description: "Create 15 habits", icon: "Layers", category: "habits", tier: "silver", xpReward: 750, goldReward: 75 },
  { key: "habits_20", title: "Habit Architect", description: "Create 20 habits", icon: "Layers", category: "habits", tier: "gold", xpReward: 1000, goldReward: 100 },
  { key: "habits_30", title: "Habit Master", description: "Create 30 habits", icon: "Layers", category: "habits", tier: "platinum", xpReward: 1500, goldReward: 150, statBonus: { stat: "intelligence", amount: 5 } },
  { key: "first_complete", title: "First Step", description: "Complete your first habit", icon: "Check", category: "habits", tier: "bronze", xpReward: 50, goldReward: 5 },
  { key: "complete_10", title: "Getting Momentum", description: "Complete habits 10 times", icon: "Check", category: "habits", tier: "bronze", xpReward: 200, goldReward: 20 },
  { key: "complete_50", title: "Building Routine", description: "Complete habits 50 times", icon: "Check", category: "habits", tier: "silver", xpReward: 400, goldReward: 40 },
  { key: "complete_100", title: "Century Mark", description: "Complete habits 100 times", icon: "Check", category: "habits", tier: "silver", xpReward: 800, goldReward: 80 },
  { key: "complete_250", title: "Quarter Thousand", description: "Complete habits 250 times", icon: "Check", category: "habits", tier: "gold", xpReward: 1200, goldReward: 120 },
  { key: "complete_500", title: "Half Millennium", description: "Complete habits 500 times", icon: "Check", category: "habits", tier: "gold", xpReward: 2000, goldReward: 200 },
  { key: "complete_1000", title: "Thousand Strong", description: "Complete habits 1,000 times", icon: "Check", category: "habits", tier: "platinum", xpReward: 4000, goldReward: 400, statBonus: { stat: "vitality", amount: 10 } },
  { key: "complete_5000", title: "Habit Legend", description: "Complete habits 5,000 times", icon: "Check", category: "habits", tier: "legendary", xpReward: 10000, goldReward: 1000, specialPower: "Legendary completion animation" },
  { key: "hard_habit_1", title: "Challenge Accepted", description: "Complete a hard difficulty habit", icon: "Sword", category: "habits", tier: "bronze", xpReward: 200, goldReward: 20 },
  { key: "hard_habit_10", title: "Challenge Seeker", description: "Complete 10 hard habits", icon: "Sword", category: "habits", tier: "silver", xpReward: 500, goldReward: 50 },
  { key: "hard_habit_50", title: "Challenge Master", description: "Complete 50 hard habits", icon: "Sword", category: "habits", tier: "gold", xpReward: 1500, goldReward: 150, statBonus: { stat: "strength", amount: 5 } },
  { key: "hard_habit_100", title: "Challenge Conqueror", description: "Complete 100 hard habits", icon: "Sword", category: "habits", tier: "platinum", xpReward: 3000, goldReward: 300, statBonus: { stat: "strength", amount: 10 } },
  { key: "category_fitness", title: "Fitness Devotee", description: "Complete 50 fitness habits", icon: "Dumbbell", category: "habits", tier: "silver", xpReward: 600, goldReward: 60, statBonus: { stat: "strength", amount: 5 } },
  { key: "category_health", title: "Health Guardian", description: "Complete 50 health habits", icon: "Heart", category: "habits", tier: "silver", xpReward: 600, goldReward: 60, statBonus: { stat: "vitality", amount: 5 } },
  { key: "category_learning", title: "Knowledge Seeker", description: "Complete 50 learning habits", icon: "BookOpen", category: "habits", tier: "silver", xpReward: 600, goldReward: 60, statBonus: { stat: "intelligence", amount: 5 } },
  { key: "category_mindfulness", title: "Inner Peace", description: "Complete 50 mindfulness habits", icon: "Heart", category: "habits", tier: "silver", xpReward: 600, goldReward: 60, statBonus: { stat: "sense", amount: 5 } },
  { key: "category_productivity", title: "Efficiency Expert", description: "Complete 50 productivity habits", icon: "Zap", category: "habits", tier: "silver", xpReward: 600, goldReward: 60, statBonus: { stat: "agility", amount: 5 } },
  { key: "perfect_day", title: "Perfect Day", description: "Complete all habits in a single day", icon: "Sparkles", category: "habits", tier: "gold", xpReward: 1000, goldReward: 100 },
  { key: "perfect_day_5", title: "Flawless Five", description: "Achieve 5 perfect days", icon: "Sparkles", category: "habits", tier: "gold", xpReward: 2000, goldReward: 200 },
  { key: "perfect_day_30", title: "Perfection Incarnate", description: "Achieve 30 perfect days", icon: "Sparkles", category: "habits", tier: "legendary", xpReward: 8000, goldReward: 800, specialPower: "Perfect day crown animation" },
  { key: "diversity_3", title: "Well-Rounded", description: "Complete habits in 3 different categories today", icon: "Circle", category: "habits", tier: "bronze", xpReward: 150, goldReward: 15 },
  { key: "diversity_5", title: "Renaissance Soul", description: "Complete habits in 5 different categories today", icon: "Circle", category: "habits", tier: "silver", xpReward: 400, goldReward: 40 },
  { key: "priority_master", title: "Priority Master", description: "Complete all priority habits for 7 days", icon: "Star", category: "habits", tier: "silver", xpReward: 700, goldReward: 70 },
  { key: "habit_veteran", title: "Habit Veteran", description: "Keep the same habit active for 90 days", icon: "Clock", category: "habits", tier: "gold", xpReward: 1500, goldReward: 150 },
  { key: "habit_ancient", title: "Ancient Wisdom", description: "Keep the same habit active for 365 days", icon: "Clock", category: "habits", tier: "legendary", xpReward: 5000, goldReward: 500, specialPower: "Ancient habit badge" },
  { key: "quick_complete", title: "Speed Runner", description: "Complete 5 habits within 1 hour", icon: "Timer", category: "habits", tier: "silver", xpReward: 400, goldReward: 40 },
  { key: "balanced_life", title: "Balanced Life", description: "Have habits in all 6 categories", icon: "Scale", category: "habits", tier: "gold", xpReward: 1000, goldReward: 100 },
  { key: "weekday_warrior", title: "Weekday Warrior", description: "Complete all weekday habits for 4 weeks", icon: "Calendar", category: "habits", tier: "gold", xpReward: 1200, goldReward: 120 },
  { key: "custom_schedule", title: "Schedule Master", description: "Create 5 habits with custom schedules", icon: "CalendarDays", category: "habits", tier: "silver", xpReward: 500, goldReward: 50 },
  { key: "reminder_guru", title: "Reminder Guru", description: "Set up reminders for 10 habits", icon: "Bell", category: "habits", tier: "silver", xpReward: 400, goldReward: 40 },
  { key: "color_coded", title: "Color Coordinated", description: "Assign colors to 10 habits", icon: "Palette", category: "habits", tier: "bronze", xpReward: 200, goldReward: 20 },
  { key: "description_writer", title: "Detail Oriented", description: "Add descriptions to 10 habits", icon: "FileText", category: "habits", tier: "bronze", xpReward: 200, goldReward: 20 },
  { key: "active_manager", title: "Active Manager", description: "Deactivate and reactivate a habit", icon: "Power", category: "habits", tier: "bronze", xpReward: 100, goldReward: 10 },

  // GOALS (91-130)
  { key: "first_goal", title: "Goal Setter", description: "Create your first goal", icon: "Target", category: "goals", tier: "bronze", xpReward: 150, goldReward: 15 },
  { key: "goals_5", title: "Ambitious", description: "Create 5 goals", icon: "Target", category: "goals", tier: "silver", xpReward: 400, goldReward: 40 },
  { key: "goals_10", title: "Visionary", description: "Create 10 goals", icon: "Target", category: "goals", tier: "gold", xpReward: 800, goldReward: 80 },
  { key: "goals_25", title: "Dream Architect", description: "Create 25 goals", icon: "Target", category: "goals", tier: "platinum", xpReward: 1500, goldReward: 150 },
  { key: "goal_complete_1", title: "Achiever", description: "Complete your first goal", icon: "Trophy", category: "goals", tier: "bronze", xpReward: 300, goldReward: 30 },
  { key: "goal_complete_5", title: "Goal Crusher", description: "Complete 5 goals", icon: "Trophy", category: "goals", tier: "silver", xpReward: 750, goldReward: 75 },
  { key: "goal_complete_10", title: "Ambitious Achiever", description: "Complete 10 goals", icon: "Trophy", category: "goals", tier: "gold", xpReward: 1500, goldReward: 150 },
  { key: "goal_complete_25", title: "Dream Realizer", description: "Complete 25 goals", icon: "Trophy", category: "goals", tier: "platinum", xpReward: 3500, goldReward: 350, statBonus: { stat: "intelligence", amount: 10 } },
  { key: "goal_complete_50", title: "Life Transformer", description: "Complete 50 goals", icon: "Trophy", category: "goals", tier: "legendary", xpReward: 7500, goldReward: 750, specialPower: "Goal mastery crown" },
  { key: "hard_goal_1", title: "Big Dreamer", description: "Complete a hard difficulty goal", icon: "Mountain", category: "goals", tier: "silver", xpReward: 500, goldReward: 50 },
  { key: "hard_goal_5", title: "Mountain Climber", description: "Complete 5 hard goals", icon: "Mountain", category: "goals", tier: "gold", xpReward: 1500, goldReward: 150 },
  { key: "hard_goal_10", title: "Peak Conqueror", description: "Complete 10 hard goals", icon: "Mountain", category: "goals", tier: "platinum", xpReward: 3000, goldReward: 300, statBonus: { stat: "willpower", amount: 10 } },
  { key: "step_complete_10", title: "Step by Step", description: "Complete 10 goal steps", icon: "ListChecks", category: "goals", tier: "bronze", xpReward: 200, goldReward: 20 },
  { key: "step_complete_50", title: "Methodical", description: "Complete 50 goal steps", icon: "ListChecks", category: "goals", tier: "silver", xpReward: 600, goldReward: 60 },
  { key: "step_complete_100", title: "Process Master", description: "Complete 100 goal steps", icon: "ListChecks", category: "goals", tier: "gold", xpReward: 1200, goldReward: 120 },
  { key: "on_time_1", title: "Punctual", description: "Complete a goal before deadline", icon: "Clock", category: "goals", tier: "bronze", xpReward: 250, goldReward: 25 },
  { key: "on_time_5", title: "Time Keeper", description: "Complete 5 goals before deadline", icon: "Clock", category: "goals", tier: "silver", xpReward: 700, goldReward: 70 },
  { key: "on_time_10", title: "Deadline Master", description: "Complete 10 goals before deadline", icon: "Clock", category: "goals", tier: "gold", xpReward: 1400, goldReward: 140 },
  { key: "early_bird_goal", title: "Early Finisher", description: "Complete a goal a week early", icon: "Rocket", category: "goals", tier: "silver", xpReward: 500, goldReward: 50 },
  { key: "month_achiever", title: "Monthly Achiever", description: "Complete a goal in under 30 days", icon: "Calendar", category: "goals", tier: "silver", xpReward: 600, goldReward: 60 },
  { key: "year_planner", title: "Year Planner", description: "Set a goal with a 1-year deadline", icon: "CalendarDays", category: "goals", tier: "silver", xpReward: 400, goldReward: 40 },
  { key: "priority_goals", title: "Priority Focused", description: "Complete 5 priority goals", icon: "Star", category: "goals", tier: "gold", xpReward: 1000, goldReward: 100 },
  { key: "goal_chain_3", title: "Chain Reaction", description: "Complete 3 progressive goals in a row", icon: "Link", category: "goals", tier: "gold", xpReward: 1500, goldReward: 150 },
  { key: "goal_chain_5", title: "Unstoppable Progress", description: "Complete 5 progressive goals", icon: "Link", category: "goals", tier: "platinum", xpReward: 2500, goldReward: 250 },
  { key: "ai_goal_1", title: "AI Collaborator", description: "Complete an AI-generated goal", icon: "Brain", category: "goals", tier: "bronze", xpReward: 300, goldReward: 30 },
  { key: "ai_goal_5", title: "AI Partner", description: "Complete 5 AI-generated goals", icon: "Brain", category: "goals", tier: "silver", xpReward: 800, goldReward: 80 },
  { key: "full_progress", title: "Full Progress", description: "Update a goal from 0% to 100%", icon: "TrendingUp", category: "goals", tier: "bronze", xpReward: 200, goldReward: 20 },
  { key: "goal_steps_5", title: "Planner", description: "Create a goal with 5+ steps", icon: "ListPlus", category: "goals", tier: "bronze", xpReward: 150, goldReward: 15 },
  { key: "goal_steps_10", title: "Master Planner", description: "Create a goal with 10+ steps", icon: "ListPlus", category: "goals", tier: "silver", xpReward: 400, goldReward: 40 },
  { key: "multi_category_goals", title: "Diverse Goals", description: "Complete goals in 5 different categories", icon: "Grid", category: "goals", tier: "gold", xpReward: 1000, goldReward: 100 },
  { key: "goal_spree", title: "Goal Spree", description: "Complete 3 goals in one week", icon: "Flame", category: "goals", tier: "gold", xpReward: 1200, goldReward: 120 },
  { key: "long_term_1", title: "Long-Term Thinker", description: "Complete a goal set 6+ months ago", icon: "Hourglass", category: "goals", tier: "gold", xpReward: 1500, goldReward: 150 },
  { key: "progressive_master", title: "Progressive Master", description: "Complete 10 progressive follow-up goals", icon: "ArrowUpRight", category: "goals", tier: "legendary", xpReward: 5000, goldReward: 500, specialPower: "Automatic goal difficulty scaling" },
  { key: "habit_from_goal", title: "Habit Creator", description: "Create a habit from a goal suggestion", icon: "Repeat", category: "goals", tier: "silver", xpReward: 400, goldReward: 40 },
  { key: "fitness_goal", title: "Fitness Achiever", description: "Complete 5 fitness goals", icon: "Dumbbell", category: "goals", tier: "silver", xpReward: 700, goldReward: 70, statBonus: { stat: "strength", amount: 5 } },
  { key: "learning_goal", title: "Knowledge Achiever", description: "Complete 5 learning goals", icon: "GraduationCap", category: "goals", tier: "silver", xpReward: 700, goldReward: 70, statBonus: { stat: "intelligence", amount: 5 } },
  { key: "personal_goal", title: "Self-Improvement", description: "Complete 5 personal goals", icon: "User", category: "goals", tier: "silver", xpReward: 700, goldReward: 70, statBonus: { stat: "willpower", amount: 5 } },
  { key: "work_goal", title: "Career Builder", description: "Complete 5 work goals", icon: "Briefcase", category: "goals", tier: "silver", xpReward: 700, goldReward: 70, statBonus: { stat: "agility", amount: 5 } },
  { key: "health_goal", title: "Health Champion", description: "Complete 5 health goals", icon: "Heart", category: "goals", tier: "silver", xpReward: 700, goldReward: 70, statBonus: { stat: "vitality", amount: 5 } },
  { key: "finance_goal", title: "Wealth Builder", description: "Complete 5 finance goals", icon: "Coins", category: "goals", tier: "silver", xpReward: 700, goldReward: 70, statBonus: { stat: "sense", amount: 5 } },

  // SPECIAL (131-160)
  { key: "first_login", title: "Welcome", description: "Log in for the first time", icon: "LogIn", category: "special", tier: "bronze", xpReward: 50, goldReward: 5 },
  { key: "profile_complete", title: "Identity Established", description: "Complete your profile", icon: "User", category: "special", tier: "bronze", xpReward: 100, goldReward: 10 },
  { key: "avatar_chosen", title: "Avatar Selected", description: "Choose your character avatar", icon: "UserCircle", category: "special", tier: "bronze", xpReward: 50, goldReward: 5 },
  { key: "first_note", title: "Scribe", description: "Create your first note", icon: "PenTool", category: "special", tier: "bronze", xpReward: 100, goldReward: 10 },
  { key: "notes_10", title: "Journal Keeper", description: "Create 10 notes", icon: "BookOpen", category: "special", tier: "silver", xpReward: 400, goldReward: 40 },
  { key: "notes_50", title: "Chronicler", description: "Create 50 notes", icon: "BookOpen", category: "special", tier: "gold", xpReward: 1000, goldReward: 100 },
  { key: "ai_summary", title: "AI Wisdom", description: "Get an AI summary for a note", icon: "Brain", category: "special", tier: "bronze", xpReward: 150, goldReward: 15 },
  { key: "library_upload", title: "Library Founder", description: "Upload your first philosophy document", icon: "Upload", category: "special", tier: "bronze", xpReward: 200, goldReward: 20 },
  { key: "library_10", title: "Library Builder", description: "Upload 10 philosophy documents", icon: "Library", category: "special", tier: "silver", xpReward: 600, goldReward: 60 },
  { key: "library_25", title: "Philosopher", description: "Upload 25 philosophy documents", icon: "Library", category: "special", tier: "gold", xpReward: 1500, goldReward: 150, statBonus: { stat: "intelligence", amount: 10 } },
  { key: "motivation_read", title: "Daily Wisdom", description: "Read your first daily motivation", icon: "Quote", category: "special", tier: "bronze", xpReward: 50, goldReward: 5 },
  { key: "motivation_week", title: "Wisdom Seeker", description: "Read motivations for 7 days", icon: "Quote", category: "special", tier: "silver", xpReward: 300, goldReward: 30 },
  { key: "tradition_esoteric", title: "Hermetic Initiate", description: "Read 10 Esoteric tradition quotes", icon: "Eye", category: "special", tier: "silver", xpReward: 400, goldReward: 40, statBonus: { stat: "sense", amount: 5 } },
  { key: "tradition_biblical", title: "Scripture Scholar", description: "Read 10 Biblical tradition quotes", icon: "Book", category: "special", tier: "silver", xpReward: 400, goldReward: 40, statBonus: { stat: "wisdom", amount: 5 } },
  { key: "tradition_quranic", title: "Quran Reader", description: "Read 10 Quranic tradition quotes", icon: "Book", category: "special", tier: "silver", xpReward: 400, goldReward: 40, statBonus: { stat: "sense", amount: 5 } },
  { key: "tradition_philosophy", title: "Ancient Philosopher", description: "Read 10 Ancient Philosophy quotes", icon: "Scroll", category: "special", tier: "silver", xpReward: 400, goldReward: 40, statBonus: { stat: "intelligence", amount: 5 } },
  { key: "tradition_metaphysical", title: "Metaphysician", description: "Read 10 Metaphysical quotes", icon: "Sparkles", category: "special", tier: "silver", xpReward: 400, goldReward: 40, statBonus: { stat: "sense", amount: 5 } },
  { key: "all_traditions", title: "Universal Wisdom", description: "Read quotes from all 5 traditions", icon: "Globe", category: "special", tier: "gold", xpReward: 1000, goldReward: 100, statBonus: { stat: "intelligence", amount: 10 }, specialPower: "Unlock special wisdom quotes" },
  { key: "gold_100", title: "Gold Collector", description: "Accumulate 100 gold", icon: "Coins", category: "special", tier: "bronze", xpReward: 100, goldReward: 0 },
  { key: "gold_500", title: "Gold Hoarder", description: "Accumulate 500 gold", icon: "Coins", category: "special", tier: "silver", xpReward: 300, goldReward: 0 },
  { key: "gold_1000", title: "Wealthy", description: "Accumulate 1,000 gold", icon: "Coins", category: "special", tier: "gold", xpReward: 600, goldReward: 0 },
  { key: "gold_5000", title: "Rich", description: "Accumulate 5,000 gold", icon: "Coins", category: "special", tier: "platinum", xpReward: 1500, goldReward: 0 },
  { key: "gold_10000", title: "Dragon's Hoard", description: "Accumulate 10,000 gold", icon: "Coins", category: "special", tier: "legendary", xpReward: 3000, goldReward: 0, specialPower: "Golden profile border" },
  { key: "analytics_view", title: "Data Driven", description: "View your analytics page", icon: "BarChart", category: "special", tier: "bronze", xpReward: 50, goldReward: 5 },
  { key: "dark_mode", title: "Shadow Walker", description: "Enable dark mode", icon: "Moon", category: "special", tier: "bronze", xpReward: 25, goldReward: 0 },
  { key: "ai_coach_chat", title: "Coach Consultation", description: "Have a conversation with AI Coach", icon: "MessageSquare", category: "special", tier: "bronze", xpReward: 150, goldReward: 15 },
  { key: "ai_coach_10", title: "Regular Coaching", description: "Have 10 AI Coach conversations", icon: "MessageSquare", category: "special", tier: "silver", xpReward: 500, goldReward: 50 },
  { key: "philosophy_ai", title: "Wisdom Integration", description: "Use philosophy docs for AI suggestions", icon: "Brain", category: "special", tier: "gold", xpReward: 800, goldReward: 80 },
  { key: "explorer", title: "Explorer", description: "Visit all pages of the app", icon: "Compass", category: "special", tier: "bronze", xpReward: 100, goldReward: 10 },
  { key: "weekend_check", title: "Weekend Warrior", description: "Check in on both Saturday and Sunday", icon: "Calendar", category: "special", tier: "bronze", xpReward: 150, goldReward: 15 },

  // STATS (161-190)
  { key: "strength_10", title: "Strong", description: "Reach 10 Strength", icon: "Sword", category: "stats", tier: "bronze", xpReward: 200, goldReward: 20 },
  { key: "strength_25", title: "Mighty", description: "Reach 25 Strength", icon: "Sword", category: "stats", tier: "silver", xpReward: 500, goldReward: 50 },
  { key: "strength_50", title: "Powerful", description: "Reach 50 Strength", icon: "Sword", category: "stats", tier: "gold", xpReward: 1000, goldReward: 100 },
  { key: "strength_100", title: "Titan Strength", description: "Reach 100 Strength", icon: "Sword", category: "stats", tier: "legendary", xpReward: 2500, goldReward: 250, specialPower: "Strength training bonus XP" },
  { key: "intelligence_10", title: "Clever", description: "Reach 10 Intelligence", icon: "Brain", category: "stats", tier: "bronze", xpReward: 200, goldReward: 20 },
  { key: "intelligence_25", title: "Wise", description: "Reach 25 Intelligence", icon: "Brain", category: "stats", tier: "silver", xpReward: 500, goldReward: 50 },
  { key: "intelligence_50", title: "Brilliant", description: "Reach 50 Intelligence", icon: "Brain", category: "stats", tier: "gold", xpReward: 1000, goldReward: 100 },
  { key: "intelligence_100", title: "Genius", description: "Reach 100 Intelligence", icon: "Brain", category: "stats", tier: "legendary", xpReward: 2500, goldReward: 250, specialPower: "Learning bonus XP" },
  { key: "vitality_10", title: "Healthy", description: "Reach 10 Vitality", icon: "Heart", category: "stats", tier: "bronze", xpReward: 200, goldReward: 20 },
  { key: "vitality_25", title: "Robust", description: "Reach 25 Vitality", icon: "Heart", category: "stats", tier: "silver", xpReward: 500, goldReward: 50 },
  { key: "vitality_50", title: "Resilient", description: "Reach 50 Vitality", icon: "Heart", category: "stats", tier: "gold", xpReward: 1000, goldReward: 100 },
  { key: "vitality_100", title: "Indomitable", description: "Reach 100 Vitality", icon: "Heart", category: "stats", tier: "legendary", xpReward: 2500, goldReward: 250, specialPower: "Health bonus XP" },
  { key: "agility_10", title: "Quick", description: "Reach 10 Agility", icon: "Zap", category: "stats", tier: "bronze", xpReward: 200, goldReward: 20 },
  { key: "agility_25", title: "Swift", description: "Reach 25 Agility", icon: "Zap", category: "stats", tier: "silver", xpReward: 500, goldReward: 50 },
  { key: "agility_50", title: "Lightning", description: "Reach 50 Agility", icon: "Zap", category: "stats", tier: "gold", xpReward: 1000, goldReward: 100 },
  { key: "agility_100", title: "Flash", description: "Reach 100 Agility", icon: "Zap", category: "stats", tier: "legendary", xpReward: 2500, goldReward: 250, specialPower: "Productivity bonus XP" },
  { key: "sense_10", title: "Aware", description: "Reach 10 Sense", icon: "Eye", category: "stats", tier: "bronze", xpReward: 200, goldReward: 20 },
  { key: "sense_25", title: "Perceptive", description: "Reach 25 Sense", icon: "Eye", category: "stats", tier: "silver", xpReward: 500, goldReward: 50 },
  { key: "sense_50", title: "Clairvoyant", description: "Reach 50 Sense", icon: "Eye", category: "stats", tier: "gold", xpReward: 1000, goldReward: 100 },
  { key: "sense_100", title: "Omniscient", description: "Reach 100 Sense", icon: "Eye", category: "stats", tier: "legendary", xpReward: 2500, goldReward: 250, specialPower: "Sense-related bonus XP" },
  { key: "willpower_10", title: "Determined", description: "Reach 10 Willpower", icon: "Flame", category: "stats", tier: "bronze", xpReward: 200, goldReward: 20 },
  { key: "willpower_25", title: "Resolute", description: "Reach 25 Willpower", icon: "Flame", category: "stats", tier: "silver", xpReward: 500, goldReward: 50 },
  { key: "willpower_50", title: "Unbreakable", description: "Reach 50 Willpower", icon: "Flame", category: "stats", tier: "gold", xpReward: 1000, goldReward: 100 },
  { key: "willpower_100", title: "Iron Will", description: "Reach 100 Willpower", icon: "Flame", category: "stats", tier: "legendary", xpReward: 2500, goldReward: 250, specialPower: "Willpower bonus XP" },
  { key: "balanced_stats_10", title: "Balanced Beginner", description: "All stats at 10+", icon: "Scale", category: "stats", tier: "silver", xpReward: 800, goldReward: 80 },
  { key: "balanced_stats_25", title: "Balanced Warrior", description: "All stats at 25+", icon: "Scale", category: "stats", tier: "gold", xpReward: 2000, goldReward: 200 },
  { key: "balanced_stats_50", title: "Perfect Balance", description: "All stats at 50+", icon: "Scale", category: "stats", tier: "platinum", xpReward: 5000, goldReward: 500, statBonus: { stat: "willpower", amount: 15 } },
  { key: "balanced_stats_100", title: "True Mastery", description: "All stats at 100+", icon: "Crown", category: "stats", tier: "legendary", xpReward: 15000, goldReward: 1500, specialPower: "Universal 5% XP boost" },
  { key: "stat_total_100", title: "Growing Power", description: "Reach 100 total stat points", icon: "TrendingUp", category: "stats", tier: "silver", xpReward: 500, goldReward: 50 },
  { key: "stat_total_500", title: "Formidable", description: "Reach 500 total stat points", icon: "TrendingUp", category: "stats", tier: "platinum", xpReward: 2500, goldReward: 250 },

  // LEGENDARY (191-200)
  { key: "ultimate_hunter", title: "Ultimate Hunter", description: "Unlock 50 achievements", icon: "Award", category: "legendary", tier: "legendary", xpReward: 5000, goldReward: 500, specialPower: "Achievement hunter badge" },
  { key: "achievement_master", title: "Achievement Master", description: "Unlock 100 achievements", icon: "Award", category: "legendary", tier: "legendary", xpReward: 10000, goldReward: 1000, specialPower: "Master collector frame" },
  { key: "completionist", title: "Completionist", description: "Unlock 150 achievements", icon: "Medal", category: "legendary", tier: "legendary", xpReward: 20000, goldReward: 2000, specialPower: "Completionist title" },
  { key: "legend", title: "Living Legend", description: "Unlock all 200 achievements", icon: "Crown", category: "legendary", tier: "legendary", xpReward: 50000, goldReward: 5000, statBonus: { stat: "willpower", amount: 50 }, specialPower: "Legendary status - Ultimate power unlocked" },
  { key: "year_one", title: "Year One", description: "Use the app for a full year", icon: "Calendar", category: "legendary", tier: "legendary", xpReward: 10000, goldReward: 1000, specialPower: "Anniversary badge" },
  { key: "shadow_monarch", title: "True Shadow Monarch", description: "Reach Level 100 with all stats at 100", icon: "Crown", category: "legendary", tier: "legendary", xpReward: 25000, goldReward: 2500, specialPower: "Shadow Monarch powers unlocked" },
  { key: "perfect_year", title: "Perfect Year", description: "365 perfect days", icon: "Sparkles", category: "legendary", tier: "legendary", xpReward: 50000, goldReward: 5000, specialPower: "Golden year aura" },
  { key: "million_xp", title: "Million XP Club", description: "Earn 1,000,000 total XP", icon: "Star", category: "legendary", tier: "legendary", xpReward: 25000, goldReward: 2500, specialPower: "Million XP particle effects" },
  { key: "habit_legend", title: "Habit Legend", description: "10,000 habit completions", icon: "Flame", category: "legendary", tier: "legendary", xpReward: 25000, goldReward: 2500, specialPower: "Legendary habit animation" },
  { key: "enlightened", title: "Enlightened One", description: "Max level, all achievements, perfect balance", icon: "Sun", category: "legendary", tier: "legendary", xpReward: 100000, goldReward: 10000, statBonus: { stat: "sense", amount: 100 }, specialPower: "Enlightenment - transcend limits" },
];
